"""
GNN-based Quantum Error Mitigation
====================================
Implements a Graph Neural Network (GNN) that learns to mitigate noise in
quantum circuit expectation values. Consumes graph-encoded circuit data
produced by generate_quantum_dataset.py.

Architecture (per the reference paper):
  - 2 × Transformer Convolution layers (multi-head attention on edges)
  - ASAPooling layers for graph-level readout
  - 2 × Dense layers (hidden_size=128)
  - Dropout regularisation throughout
  - Input: circuit DAG graph + noisy expectation values
  - Output: mitigated (near-ideal) expectation values

Usage
-----
# 1. Generate data (if you haven't already):
    python generate_quantum_dataset.py --num_circuits 200 --output dataset.json

# 2. Train the GNN:
    python gnn_quantum_error_mitigation.py --dataset dataset.json --epochs 100

# 3. Evaluate / run inference:
    python gnn_quantum_error_mitigation.py --dataset dataset.json --mode eval --checkpoint best_model.pt
"""

import argparse
import json
import math
import os
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch_geometric.data import Data, HeteroData, Dataset
from torch_geometric.loader import DataLoader
from torch_geometric.nn import (
    TransformerConv,
    SAGPooling,
    global_mean_pool,
    global_max_pool,
    Linear,
)
from torch_geometric.utils import to_undirected
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# ---------------------------------------------------------------------------
# 1.  Dataset: parse JSON graph encoding → PyG Data objects
# ---------------------------------------------------------------------------

NODE_FEAT_DIM  = 22   # DAGOpNode feature dimension (from generate_quantum_dataset.py)
EDGE_FEAT_DIM  = 3    # wire features: T1, T2, readout_error


def _pad_or_truncate(feat: list, target_dim: int) -> list:
    """Ensure a feature vector is exactly target_dim elements."""
    if len(feat) >= target_dim:
        return feat[:target_dim]
    return feat + [0.0] * (target_dim - len(feat))


def sample_to_pyg(sample: dict, obs_idx: int) -> Data | None:
    """
    Convert one dataset sample (one observable) into a PyG Data object.

    The graph has only DAGOpNode nodes (gate nodes).  DAGInNode/DAGOutNode
    are boundary nodes with no meaningful features and are excluded.
    Edges are the op→op wires from the circuit DAG.

    Parameters
    ----------
    sample   : dict with keys circuit_graph, noisy_exp_values, ideal_exp_value
    obs_idx  : which observable index to use as the label

    Returns
    -------
    PyG Data or None if the circuit graph is degenerate.
    """
    graph = sample["circuit_graph"]
    op_feats = graph["nodes"]["DAGOpNode"]

    if not op_feats:
        return None

    # ---- Node features ----
    x = torch.tensor(
        [_pad_or_truncate(f, NODE_FEAT_DIM) for f in op_feats],
        dtype=torch.float
    )

    # ---- Edge index (op → op wires only) ----
    op_op_edges = graph["edges"].get("DAGOpNode_wire_DAGOpNode", {})
    src_list = op_op_edges.get("edge_index", [[], []])[0]
    dst_list = op_op_edges.get("edge_index", [[], []])[1]
    edge_attrs = op_op_edges.get("edge_attr", [])

    if src_list:
        edge_index = torch.tensor([src_list, dst_list], dtype=torch.long)
        edge_attr  = torch.tensor(
            [_pad_or_truncate(a, EDGE_FEAT_DIM) for a in edge_attrs],
            dtype=torch.float
        )
        # Make undirected so information can flow both ways
        edge_index, edge_attr = to_undirected(edge_index, edge_attr, reduce="mean")
    else:
        edge_index = torch.zeros((2, 0), dtype=torch.long)
        edge_attr  = torch.zeros((0, EDGE_FEAT_DIM), dtype=torch.float)

    # ---- Noisy expectation value (input signal) ----
    # noisy_exp_values is a list of trials, each a list of obs values
    noisy_trials = sample["noisy_exp_values"]   # shape: [n_trials, n_obs]
    noisy_val    = float(np.mean([t[obs_idx] for t in noisy_trials]))

    # ---- Ideal expectation value (label) ----
    ideal_val = float(sample["ideal_exp_value"][obs_idx])

    # ---- Global graph feature: noisy value appended to each node ----
    noisy_tensor = torch.full((x.size(0), 1), noisy_val, dtype=torch.float)
    x_aug = torch.cat([x, noisy_tensor], dim=1)   # [N, NODE_FEAT_DIM + 1]

    data = Data(
        x          = x_aug,
        edge_index = edge_index,
        edge_attr  = edge_attr,
        y          = torch.tensor([[ideal_val]], dtype=torch.float),
        noisy_val  = torch.tensor([[noisy_val]], dtype=torch.float),
    )
    return data


class QuantumCircuitDataset(Dataset):
    """
    PyG Dataset that converts the JSON dataset generated by
    generate_quantum_dataset.py into graph data objects.

    Each circuit × observable pair becomes one graph sample.
    """

    def __init__(self, samples: list[dict], transform=None):
        super().__init__(transform=transform)
        self._data_list: list[Data] = []

        for sample in samples:
            n_obs = len(sample["ideal_exp_value"])
            for obs_idx in range(n_obs):
                data = sample_to_pyg(sample, obs_idx)
                if data is not None:
                    self._data_list.append(data)

        print(f"  Loaded {len(self._data_list)} graph samples "
              f"from {len(samples)} circuits.")

    def len(self):
        return len(self._data_list)

    def get(self, idx):
        return self._data_list[idx]


# ---------------------------------------------------------------------------
# 2.  GNN Model
# ---------------------------------------------------------------------------

class QuantumErrorMitigationGNN(nn.Module):
    """
    GNN for quantum error mitigation.

    Architecture:
        TransformerConv (layer 1)  →  ASAPooling (partial)
        TransformerConv (layer 2)  →  ASAPooling (full graph readout)
        Dense layer 1 (128)
        Dense layer 2 (128)
        Output head (1 per observable, i.e. 1 here)

    The noisy expectation value is concatenated to node features before the
    GNN layers, so the model can learn the correction Δ = ideal - noisy.
    """

    def __init__(
        self,
        node_feat_dim   : int   = NODE_FEAT_DIM + 1,   # +1 for noisy value
        edge_feat_dim   : int   = EDGE_FEAT_DIM,
        hidden_size     : int   = 128,
        num_heads       : int   = 4,
        dropout         : float = 0.2,
        add_self_loops  : bool  = True,
    ):
        super().__init__()

        self.dropout_rate = dropout

        # ---- Input projection ----
        self.input_proj = Linear(node_feat_dim, hidden_size)

        # ---- Transformer Convolution Layer 1 ----
        self.conv1 = TransformerConv(
            in_channels  = hidden_size,
            out_channels = hidden_size // num_heads,
            heads        = num_heads,
            edge_dim     = edge_feat_dim,
            dropout      = dropout,
            concat       = True,
            beta         = True,          # use key/query/value beta (more expressive)
            root_weight  = True,
        )
        self.bn1 = nn.BatchNorm1d(hidden_size)

        # ---- SAGPooling after layer 1 (down-samples graph) ----
        self.pool1 = SAGPooling(
            in_channels = hidden_size,
            ratio       = 0.8,            # keep 80% of nodes
            GNN         = TransformerConv,
        )

        # ---- Transformer Convolution Layer 2 ----
        self.conv2 = TransformerConv(
            in_channels  = hidden_size,
            out_channels = hidden_size // num_heads,
            heads        = num_heads,
            edge_dim     = edge_feat_dim,
            dropout      = dropout,
            concat       = True,
            beta         = True,
            root_weight  = True,
        )
        self.bn2 = nn.BatchNorm1d(hidden_size)

        # ---- SAGPooling after layer 2 ----
        self.pool2 = SAGPooling(
            in_channels = hidden_size,
            ratio       = 0.5,
            GNN         = TransformerConv,
        )

        # ---- Global pooling fallback (in case pool2 returns 0 nodes) ----
        # This also combines max and mean for richer graph representation.
        graph_repr_dim = hidden_size * 2 + 1   # max+mean pooled + noisy_val

        # ---- Dense layers ----
        self.fc1    = nn.Linear(graph_repr_dim, hidden_size)
        self.fc2    = nn.Linear(hidden_size,    hidden_size)
        self.output = nn.Linear(hidden_size,    1)

        self.dropout = nn.Dropout(p=dropout)

    def forward(self, data: Data) -> torch.Tensor:
        x, edge_index, edge_attr = data.x, data.edge_index, data.edge_attr
        batch     = data.batch
        noisy_val = data.noisy_val           # [B, 1]

        # Extract and validate edge attributes
        if edge_attr is None or edge_attr.size(0) == 0:
            edge_attr = torch.zeros(
                (edge_index.size(1), EDGE_FEAT_DIM),
                device=x.device
            )

        # ---- Input projection + activation ----
        x = F.elu(self.input_proj(x))
        x = self.dropout(x)

        # ---- TransformerConv Layer 1 ----
        x = self.conv1(x, edge_index, edge_attr)
        x = self.bn1(x)
        x = F.elu(x)
        x = self.dropout(x)

        # ---- SAGPooling 1 ----
        # SAGPooling returns (x, edge_index, edge_attr, batch, perm, score)
        if edge_index.size(1) > 0:
            x, edge_index, edge_attr, batch, _, _ = self.pool1(
                x, edge_index, edge_attr=edge_attr, batch=batch
            )
        # Ensure edge_attr matches edge_index after pooling
        if edge_attr is None or edge_attr.size(0) != edge_index.size(1):
            edge_attr = torch.zeros(
                (edge_index.size(1), EDGE_FEAT_DIM), device=x.device
            )

        # ---- TransformerConv Layer 2 ----
        x = self.conv2(x, edge_index, edge_attr)
        x = self.bn2(x)
        x = F.elu(x)
        x = self.dropout(x)

        # ---- Global readout (mean + max pooling → richer representation) ----
        x_mean = global_mean_pool(x, batch)      # [B, hidden]
        x_max  = global_max_pool(x, batch)       # [B, hidden]
        graph_repr = torch.cat([x_mean, x_max, noisy_val], dim=-1)   # [B, 2H+1]

        # ---- Dense layers ----
        out = F.elu(self.fc1(graph_repr))
        out = self.dropout(out)
        out = F.elu(self.fc2(out))
        out = self.dropout(out)
        out = self.output(out)                   # [B, 1]

        return out


# ---------------------------------------------------------------------------
# 3.  Training utilities
# ---------------------------------------------------------------------------

def feature_normalize(dataset: QuantumCircuitDataset) -> tuple[np.ndarray, np.ndarray]:
    """
    Compute per-feature mean and std over the training set for normalisation.
    Returns (mean, std) arrays of shape [node_feat_dim].
    """
    all_feats = []
    for data in dataset:
        all_feats.append(data.x.numpy())
    all_feats = np.vstack(all_feats)
    mean = all_feats.mean(axis=0)
    std  = all_feats.std(axis=0) + 1e-8
    return mean, std


def normalize_dataset(
    dataset : QuantumCircuitDataset,
    mean    : np.ndarray,
    std     : np.ndarray,
) -> None:
    """Apply z-score normalization in-place."""
    mean_t = torch.tensor(mean, dtype=torch.float)
    std_t  = torch.tensor(std,  dtype=torch.float)
    for data in dataset:
        data.x = (data.x - mean_t) / std_t


def train_one_epoch(
    model      : nn.Module,
    loader     : DataLoader,
    optimizer  : torch.optim.Optimizer,
    device     : torch.device,
) -> float:
    model.train()
    total_loss = 0.0
    total_samples = 0

    for batch in loader:
        batch = batch.to(device)
        optimizer.zero_grad()

        pred = model(batch)
        loss = F.mse_loss(pred, batch.y)

        loss.backward()
        # Gradient clipping for stability
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        total_loss    += loss.item() * batch.num_graphs
        total_samples += batch.num_graphs

    return total_loss / total_samples


@torch.no_grad()
def evaluate(
    model  : nn.Module,
    loader : DataLoader,
    device : torch.device,
) -> dict:
    model.eval()
    preds, targets, noisy_vals = [], [], []

    for batch in loader:
        batch = batch.to(device)
        pred  = model(batch)
        preds.append(pred.cpu())
        targets.append(batch.y.cpu())
        noisy_vals.append(batch.noisy_val.cpu())

    preds      = torch.cat(preds).numpy().flatten()
    targets    = torch.cat(targets).numpy().flatten()
    noisy_vals = torch.cat(noisy_vals).numpy().flatten()

    mse_mitigated = float(np.mean((preds - targets) ** 2))
    mse_noisy     = float(np.mean((noisy_vals - targets) ** 2))
    mae_mitigated = float(np.mean(np.abs(preds - targets)))
    mae_noisy     = float(np.mean(np.abs(noisy_vals - targets)))

    # R² score
    ss_res = np.sum((preds - targets) ** 2)
    ss_tot = np.sum((targets - targets.mean()) ** 2) + 1e-12
    r2     = 1.0 - ss_res / ss_tot

    # Mitigation ratio: how much of the noise error was corrected
    noise_error     = mse_noisy
    remaining_error = mse_mitigated
    mitigation_ratio = 1.0 - remaining_error / (noise_error + 1e-12)

    # return {
    #     "mse"              : mse_mitigated,
    #     "mae"              : mae_mitigated,
    #     "mse_noisy"        : mse_noisy,
    #     "mae_noisy"        : mae_noisy,
    #     "r2"               : r2,
    #     "mitigation_ratio" : mitigation_ratio,
    # }

    return {
        "mse" : mse_mitigated,
        "mae" : mae_mitigated,
        "mse_noisy" : mse_noisy,
        "mae_noisy" : mae_noisy,
        "r2" : r2,
        "mitigation_ratio" : mitigation_ratio,
        # ADD THESE THREE LINES BELOW:
        "_preds": preds,      
        "_targets": targets,  
        "_noisy": noisy_vals  
    }


# ---------------------------------------------------------------------------
# 4.  Main training / evaluation pipeline
# ---------------------------------------------------------------------------

def run_training(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n{'='*60}")
    print(f"  GNN Quantum Error Mitigation — Training")
    print(f"{'='*60}")
    print(f"  Device  : {device}")
    print(f"  Dataset : {args.dataset}")
    print(f"  Epochs  : {args.epochs}")
    print(f"  Batch   : {args.batch_size}")
    print(f"  LR      : {args.lr}")
    print(f"{'='*60}\n")

    # ---- Load data ----
    print("Loading dataset ...")
    with open(args.dataset) as f:
        raw = json.load(f)

    # Split at the circuit level to avoid data leakage across observables
    train_raw, test_raw = train_test_split(raw, test_size=0.15, random_state=42)
    train_raw, val_raw  = train_test_split(train_raw, test_size=0.15, random_state=42)

    print(f"  Circuits  — train: {len(train_raw)}  val: {len(val_raw)}  test: {len(test_raw)}")

    train_ds = QuantumCircuitDataset(train_raw)
    val_ds   = QuantumCircuitDataset(val_raw)
    test_ds  = QuantumCircuitDataset(test_raw)

    # ---- Normalise node features ----
    print("Normalising features ...")
    mean, std = feature_normalize(train_ds)
    normalize_dataset(train_ds, mean, std)
    normalize_dataset(val_ds,   mean, std)
    normalize_dataset(test_ds,  mean, std)

    # Save normalisation stats alongside checkpoint
    norm_path = Path(args.checkpoint).with_suffix(".norm.npz")
    np.savez(norm_path, mean=mean, std=std)

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch_size, shuffle=False, num_workers=0)
    test_loader  = DataLoader(test_ds,  batch_size=args.batch_size, shuffle=False, num_workers=0)

    # ---- Build model ----
    model = QuantumErrorMitigationGNN(
        node_feat_dim  = NODE_FEAT_DIM + 1,
        edge_feat_dim  = EDGE_FEAT_DIM,
        hidden_size    = args.hidden_size,
        num_heads      = args.num_heads,
        dropout        = args.dropout,
    ).to(device)

    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"\n  Model parameters: {n_params:,}\n")

    optimizer = Adam(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = ReduceLROnPlateau(optimizer, mode="min", patience=10, factor=0.5)


    best_val_mse = math.inf
    history = {"train_mse": [], "val_mse": [], "val_r2": [], "val_mitigation_ratio": []}

    # ---- Training loop ----
    for epoch in range(1, args.epochs + 1):
        t0 = time.time()
        train_mse = train_one_epoch(model, train_loader, optimizer, device)
        val_metrics = evaluate(model, val_loader, device)

        scheduler.step(val_metrics["mse"])

        history["train_mse"].append(train_mse)
        history["val_mse"].append(val_metrics["mse"])
        history["val_r2"].append(val_metrics["r2"])
        history["val_mitigation_ratio"].append(val_metrics["mitigation_ratio"])

        # Save best model
        if val_metrics["mse"] < best_val_mse:
            best_val_mse = val_metrics["mse"]
            torch.save(
                {"model_state": model.state_dict(), "args": vars(args)},
                args.checkpoint,
            )
            flag = " ← best"
        else:
            flag = ""

        elapsed = time.time() - t0
        print(
            f"  Epoch {epoch:>4}/{args.epochs}"
            f"  train_MSE={train_mse:.5f}"
            f"  val_MSE={val_metrics['mse']:.5f}"
            f"  val_R²={val_metrics['r2']:.4f}"
            f"  mitigation={val_metrics['mitigation_ratio']*100:.1f}%"
            f"  ({elapsed:.1f}s){flag}"
        )

    # ---- Final test evaluation ----
    print(f"\n{'='*60}")
    print("  Final Test Evaluation (best checkpoint)")
    print(f"{'='*60}")
    ckpt = torch.load(args.checkpoint, map_location=device)
    model.load_state_dict(ckpt["model_state"])
    test_metrics = evaluate(model, test_loader, device)

    improvement_factor = test_metrics['mse_noisy'] / (test_metrics['mse'] + 1e-12)

    print(f"  MSE  (mitigated) : {test_metrics['mse']:.6f}")
    print(f"  MSE  (noisy)     : {test_metrics['mse_noisy']:.6f}")
    print(f"  MAE  (mitigated) : {test_metrics['mae']:.6f}")
    print(f"  MAE  (noisy)     : {test_metrics['mae_noisy']:.6f}")
    print(f"  R²               : {test_metrics['r2']:.4f}")
    print(f"  Mitigation ratio : {test_metrics['mitigation_ratio']*100:.2f}%")
    print(f"  Improvement factor : {improvement_factor:.2f}x")

    # Save training history
    history_path = Path(args.checkpoint).with_suffix(".history.json")
    with open(history_path, "w") as f:
        json.dump(history, f, indent=2)
    print(f"\n  History saved → {history_path}")
    print(f"  Best model  saved → {args.checkpoint}")
    print(f"  Norm stats  saved → {norm_path}")


def run_inference(args):
    """Load a trained model and run inference on a dataset."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n{'='*60}")
    print("  GNN Quantum Error Mitigation — Inference")
    print(f"{'='*60}")

    with open(args.dataset) as f:
        raw = json.load(f)

    ds = QuantumCircuitDataset(raw)

    # Load normalisation stats
    norm_path = Path(args.checkpoint).with_suffix(".norm.npz")
    if norm_path.exists():
        npz  = np.load(norm_path)
        mean, std = npz["mean"], npz["std"]
        normalize_dataset(ds, mean, std)
        print(f"  Applied normalisation from {norm_path}")
    else:
        print("  Warning: no normalisation file found — features not normalised")

    loader = DataLoader(ds, batch_size=args.batch_size, shuffle=False, num_workers=0)

    ckpt  = torch.load(args.checkpoint, map_location=device)
    saved = ckpt.get("args", {})

    model = QuantumErrorMitigationGNN(
        node_feat_dim = NODE_FEAT_DIM + 1,
        edge_feat_dim = EDGE_FEAT_DIM,
        hidden_size   = saved.get("hidden_size", 128),
        num_heads     = saved.get("num_heads",   4),
        dropout       = 0.0,         # no dropout at inference
    ).to(device)
    model.load_state_dict(ckpt["model_state"])

    metrics = evaluate(model, loader, device)
    print(f"\n  MSE  (mitigated) : {metrics['mse']:.6f}")
    print(f"  MSE  (noisy)     : {metrics['mse_noisy']:.6f}")
    print(f"  R²               : {metrics['r2']:.4f}")
    print(f"  Mitigation ratio : {metrics['mitigation_ratio']*100:.2f}%")


# ---------------------------------------------------------------------------
# 5.  CLI
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        description="GNN Quantum Error Mitigation",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--dataset",
        type=str, default="quantum_dataset.json",
        help="Path to JSON dataset produced by generate_quantum_dataset.py"
    )
    p.add_argument(
        "--mode",
        choices=["train", "eval"],
        default="train",
        help="'train' to fit the model; 'eval' to run inference with a saved checkpoint"
    )
    p.add_argument(
        "--checkpoint",
        type=str, default="best_model.pt",
        help="Path to save (train) or load (eval) the model checkpoint"
    )
    p.add_argument("--epochs",       type=int,   default=100)
    p.add_argument("--batch_size",   type=int,   default=32)
    p.add_argument("--lr",           type=float, default=1e-3)
    p.add_argument("--hidden_size",  type=int,   default=128)
    p.add_argument("--num_heads",    type=int,   default=4,
                   help="Number of attention heads per TransformerConv layer")
    p.add_argument("--dropout",      type=float, default=0.2)
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()

    if args.mode == "train":
        run_training(args)
    else:
        run_inference(args)
